// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package model

import (
	"database/sql/driver"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"strings"
)

const (
	EnglishAudioDub  EnglishAudio = "dub"
	EnglishAudioSub  EnglishAudio = "sub"
	EnglishAudioNone EnglishAudio = "none"
)

var ErrInvalidEnglishAudio = fmt.Errorf("not a valid EnglishAudio, try [%s]", strings.Join(_EnglishAudioNames, ", "))

var _EnglishAudioNames = []string{
	string(EnglishAudioDub),
	string(EnglishAudioSub),
	string(EnglishAudioNone),
}

// EnglishAudioNames returns a list of possible string values of EnglishAudio.
func EnglishAudioNames() []string {
	tmp := make([]string, len(_EnglishAudioNames))
	copy(tmp, _EnglishAudioNames)
	return tmp
}

// EnglishAudioValues returns a list of the values for EnglishAudio
func EnglishAudioValues() []EnglishAudio {
	return []EnglishAudio{
		EnglishAudioDub,
		EnglishAudioSub,
		EnglishAudioNone,
	}
}

// String implements the Stringer interface.
func (x EnglishAudio) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x EnglishAudio) IsValid() bool {
	_, err := ParseEnglishAudio(string(x))
	return err == nil
}

var _EnglishAudioValue = map[string]EnglishAudio{
	"dub":  EnglishAudioDub,
	"sub":  EnglishAudioSub,
	"none": EnglishAudioNone,
}

// ParseEnglishAudio attempts to convert a string to a EnglishAudio.
func ParseEnglishAudio(name string) (EnglishAudio, error) {
	if x, ok := _EnglishAudioValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _EnglishAudioValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return EnglishAudio(""), fmt.Errorf("%s is %w", name, ErrInvalidEnglishAudio)
}

// MarshalText implements the text marshaller method.
func (x EnglishAudio) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *EnglishAudio) UnmarshalText(text []byte) error {
	tmp, err := ParseEnglishAudio(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var errEnglishAudioNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *EnglishAudio) Scan(value interface{}) (err error) {
	if value == nil {
		*x = EnglishAudio("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseEnglishAudio(v)
	case []byte:
		*x, err = ParseEnglishAudio(string(v))
	case EnglishAudio:
		*x = v
	case *EnglishAudio:
		if v == nil {
			return errEnglishAudioNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errEnglishAudioNilPtr
		}
		*x, err = ParseEnglishAudio(*v)
	default:
		return errors.New("invalid type for EnglishAudio")
	}

	return
}

// Value implements the driver Valuer interface.
func (x EnglishAudio) Value() (driver.Value, error) {
	return x.String(), nil
}

type NullEnglishAudio struct {
	EnglishAudio EnglishAudio
	Valid        bool
	Set          bool
}

func NewNullEnglishAudio(val interface{}) (x NullEnglishAudio) {
	err := x.Scan(val) // yes, we ignore this error, it will just be an invalid value.
	_ = err            // make any errcheck linters happy
	return
}

// Scan implements the Scanner interface.
func (x *NullEnglishAudio) Scan(value interface{}) (err error) {
	if value == nil {
		x.EnglishAudio, x.Valid = EnglishAudio(""), false
		return
	}

	err = x.EnglishAudio.Scan(value)
	x.Valid = (err == nil)
	return
}

// Value implements the driver Valuer interface.
func (x NullEnglishAudio) Value() (driver.Value, error) {
	if !x.Valid {
		return nil, nil
	}
	return x.EnglishAudio.String(), nil
}

// MarshalJSON correctly serializes a NullEnglishAudio to JSON.
func (n NullEnglishAudio) MarshalJSON() ([]byte, error) {
	const nullStr = "null"
	if n.Valid {
		return json.Marshal(n.EnglishAudio)
	}
	return []byte(nullStr), nil
}

// UnmarshalJSON correctly deserializes a NullEnglishAudio from JSON.
func (n *NullEnglishAudio) UnmarshalJSON(b []byte) error {
	n.Set = true
	var x interface{}
	err := json.Unmarshal(b, &x)
	if err != nil {
		return err
	}
	err = n.Scan(x)
	return err
}

// MarshalGQL correctly serializes a NullEnglishAudio to GraphQL.
func (n NullEnglishAudio) MarshalGQL(w io.Writer) {
	bytes, err := json.Marshal(n)
	if err == nil {
		_, _ = w.Write(bytes)
	}
}

// UnmarshalGQL correctly deserializes a NullEnglishAudio from GraphQL.
func (n *NullEnglishAudio) UnmarshalGQL(v any) error {
	if v == nil {
		return nil
	}
	str, ok := v.(string)
	if !ok {
		return errors.New("value is not a string")
	}
	if str == "null" {
		return nil
	}
	return n.UnmarshalJSON([]byte("\"" + str + "\""))
}
