// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package model

import (
	"database/sql/driver"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"strings"
)

const (
	ReleaseGranularityEpisode        ReleaseGranularity = "episode"
	ReleaseGranularityMultiEpisode   ReleaseGranularity = "multi_episode"
	ReleaseGranularityPartialSeason  ReleaseGranularity = "partial_season"
	ReleaseGranularitySeason         ReleaseGranularity = "season"
	ReleaseGranularityMultiSeason    ReleaseGranularity = "multi_season"
	ReleaseGranularityCompleteSeries ReleaseGranularity = "complete_series"
)

var ErrInvalidReleaseGranularity = fmt.Errorf("not a valid ReleaseGranularity, try [%s]", strings.Join(_ReleaseGranularityNames, ", "))

var _ReleaseGranularityNames = []string{
	string(ReleaseGranularityEpisode),
	string(ReleaseGranularityMultiEpisode),
	string(ReleaseGranularityPartialSeason),
	string(ReleaseGranularitySeason),
	string(ReleaseGranularityMultiSeason),
	string(ReleaseGranularityCompleteSeries),
}

// ReleaseGranularityNames returns a list of possible string values of ReleaseGranularity.
func ReleaseGranularityNames() []string {
	tmp := make([]string, len(_ReleaseGranularityNames))
	copy(tmp, _ReleaseGranularityNames)
	return tmp
}

// ReleaseGranularityValues returns a list of the values for ReleaseGranularity
func ReleaseGranularityValues() []ReleaseGranularity {
	return []ReleaseGranularity{
		ReleaseGranularityEpisode,
		ReleaseGranularityMultiEpisode,
		ReleaseGranularityPartialSeason,
		ReleaseGranularitySeason,
		ReleaseGranularityMultiSeason,
		ReleaseGranularityCompleteSeries,
	}
}

// String implements the Stringer interface.
func (x ReleaseGranularity) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ReleaseGranularity) IsValid() bool {
	_, err := ParseReleaseGranularity(string(x))
	return err == nil
}

var _ReleaseGranularityValue = map[string]ReleaseGranularity{
	"episode":         ReleaseGranularityEpisode,
	"multi_episode":   ReleaseGranularityMultiEpisode,
	"partial_season":  ReleaseGranularityPartialSeason,
	"season":          ReleaseGranularitySeason,
	"multi_season":    ReleaseGranularityMultiSeason,
	"complete_series": ReleaseGranularityCompleteSeries,
}

// ParseReleaseGranularity attempts to convert a string to a ReleaseGranularity.
func ParseReleaseGranularity(name string) (ReleaseGranularity, error) {
	if x, ok := _ReleaseGranularityValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _ReleaseGranularityValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return ReleaseGranularity(""), fmt.Errorf("%s is %w", name, ErrInvalidReleaseGranularity)
}

// MarshalText implements the text marshaller method.
func (x ReleaseGranularity) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ReleaseGranularity) UnmarshalText(text []byte) error {
	tmp, err := ParseReleaseGranularity(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var errReleaseGranularityNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *ReleaseGranularity) Scan(value interface{}) (err error) {
	if value == nil {
		*x = ReleaseGranularity("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseReleaseGranularity(v)
	case []byte:
		*x, err = ParseReleaseGranularity(string(v))
	case ReleaseGranularity:
		*x = v
	case *ReleaseGranularity:
		if v == nil {
			return errReleaseGranularityNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errReleaseGranularityNilPtr
		}
		*x, err = ParseReleaseGranularity(*v)
	default:
		return errors.New("invalid type for ReleaseGranularity")
	}

	return
}

// Value implements the driver Valuer interface.
func (x ReleaseGranularity) Value() (driver.Value, error) {
	return x.String(), nil
}

type NullReleaseGranularity struct {
	ReleaseGranularity ReleaseGranularity
	Valid              bool
	Set                bool
}

func NewNullReleaseGranularity(val interface{}) (x NullReleaseGranularity) {
	err := x.Scan(val) // yes, we ignore this error, it will just be an invalid value.
	_ = err            // make any errcheck linters happy
	return
}

// Scan implements the Scanner interface.
func (x *NullReleaseGranularity) Scan(value interface{}) (err error) {
	if value == nil {
		x.ReleaseGranularity, x.Valid = ReleaseGranularity(""), false
		return
	}

	err = x.ReleaseGranularity.Scan(value)
	x.Valid = (err == nil)
	return
}

// Value implements the driver Valuer interface.
func (x NullReleaseGranularity) Value() (driver.Value, error) {
	if !x.Valid {
		return nil, nil
	}
	return x.ReleaseGranularity.String(), nil
}

// MarshalJSON correctly serializes a NullReleaseGranularity to JSON.
func (n NullReleaseGranularity) MarshalJSON() ([]byte, error) {
	const nullStr = "null"
	if n.Valid {
		return json.Marshal(n.ReleaseGranularity)
	}
	return []byte(nullStr), nil
}

// UnmarshalJSON correctly deserializes a NullReleaseGranularity from JSON.
func (n *NullReleaseGranularity) UnmarshalJSON(b []byte) error {
	n.Set = true
	var x interface{}
	err := json.Unmarshal(b, &x)
	if err != nil {
		return err
	}
	err = n.Scan(x)
	return err
}

// MarshalGQL correctly serializes a NullReleaseGranularity to GraphQL.
func (n NullReleaseGranularity) MarshalGQL(w io.Writer) {
	bytes, err := json.Marshal(n)
	if err == nil {
		_, _ = w.Write(bytes)
	}
}

// UnmarshalGQL correctly deserializes a NullReleaseGranularity from GraphQL.
func (n *NullReleaseGranularity) UnmarshalGQL(v any) error {
	if v == nil {
		return nil
	}
	str, ok := v.(string)
	if !ok {
		return errors.New("value is not a string")
	}
	if str == "null" {
		return nil
	}
	return n.UnmarshalJSON([]byte("\"" + str + "\""))
}
