'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

function deferred() {
  let resolve;
  const promise = new Promise(done => { resolve = done; });
  return { promise, resolve };
}

function snapshot() {
  return { fields: {
    log_level: { sensitive: false, current: 'info', default: 'info', source: 'startup', overridden: false },
    sonarr_base_url: { sensitive: false, current: 'http://demo.invalid:8989', default: '', source: 'override', overridden: true },
    tmdb_api_key: { sensitive: true, configured: true, source: 'override', overridden: true },
  } };
}

function decode(value) {
  return value.replaceAll('&quot;', '"').replaceAll('&#39;', "'").replaceAll('&lt;', '<').replaceAll('&gt;', '>').replaceAll('&amp;', '&');
}

function controller() {
  const elements = new Map();
  const document = { activeElement: null, getElementById: id => elements.get(id) || null };
  function element(id, attributes = {}) {
    const el = {
      id, attributes, dataset: {}, value: attributes.value || '', textContent: '',
      hidden: !!attributes.hidden, disabled: !!attributes.disabled,
      selectionStart: 0, selectionEnd: 0,
      setAttribute(name, value) { this.attributes[name] = value; },
      focus() { document.activeElement = this; },
      setSelectionRange(start, end) { this.selectionStart = start; this.selectionEnd = end; },
    };
    elements.set(id, el);
    return el;
  }
  for (const id of ['settingsStatus', 'settingsReload', 'settingsSearch', 'settingsSummary', 'settingsEmpty', 'tzKeyDisplay', 'tmdbStatus', 'dashKeyDisplay']) element(id);
  const grid = element('settingsGrid');
  grid.contains = el => el && el.id.startsWith('setting-');
  let markup = '';
  Object.defineProperty(grid, 'innerHTML', {
    get() { return markup; },
    set(value) {
      markup = value;
      for (const id of elements.keys()) if (id.startsWith('setting-')) elements.delete(id);
      // The harness models the controls generated by the production renderer;
      // async interactions call the actual controller, not a copied algorithm.
      for (const tag of value.matchAll(/<\w+\s+([^>]+)>/g)) {
        const attributes = {};
        for (const pair of tag[1].matchAll(/([\w-]+)="([^"]*)"/g)) attributes[pair[1]] = decode(pair[2]);
        if (!attributes.id) continue;
        attributes.hidden = /(?:^|\s)hidden(?:\s|$)/.test(tag[1]);
        const el = element(attributes.id, attributes);
        if (attributes['data-sensitive']) el.dataset.sensitive = attributes['data-sensitive'];
      }
    },
  });
  const calls = [];
  const toasts = [];
  let data = snapshot();
  let handler = null;
  const api = async (url, opts = {}) => {
    calls.push({ url, opts });
    if (handler) return handler(url, opts);
    if (url === '/api/settings') return structuredClone(data);
    if (url === '/api/auth/tiers') return { apiKey: false };
    const key = url.split('/').at(-1);
    const field = data.fields[key];
    if (field && opts.method === 'PUT') {
      const value = JSON.parse(opts.body).value;
      data.fields[key] = { ...field, overridden: true, source: 'override', ...(field.sensitive ? { configured: true } : { current: value }) };
      return { key };
    }
    if (field && opts.method === 'DELETE') {
      data.fields[key] = { ...field, overridden: false, source: 'startup', ...(field.sensitive ? { configured: false } : { current: field.default }) };
      return { status: 'deleted' };
    }
    return null;
  };
  const context = vm.createContext({ document, api, Date,
    escHtml: value => String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;'),
    toast: (...args) => toasts.push(args), loadAuditLog() {}, loadAuthStatus() {},
  });
  const source = fs.readFileSync(path.join(__dirname, '../static/js/app.js'), 'utf8');
  const start = source.indexOf('/* ── Settings ─');
  const end = source.indexOf('async function loadAuditLog()', start);
  const sharedStart = source.indexOf('/* ── Integration configuration ─');
  const sharedEnd = source.indexOf('function _arrName(', sharedStart);
  assert.ok(start >= 0 && end > start && sharedEnd > sharedStart);
  vm.runInContext(source.slice(sharedStart, sharedEnd) + source.slice(start, end) + '\nthis.settings = { loadSettings, saveSetting, resetSetting, cancelSettingReset, editSetting, filterSettings };', context);
  return {
    ...context.settings, get: id => elements.get(id), document, calls, toasts,
    get markup() { return markup; },
    get data() { return data; }, set data(value) { data = value; },
    handle(value) { handler = value; },
    edit(key, value) { this.get(`setting-${key}`).value = value; this.editSetting(key); },
    writes() { return calls.filter(call => ['PUT', 'DELETE'].includes(call.opts.method)); },
  };
}

test('initial configuration failure is visible and a reload recovers labeled controls', async () => {
  const c = controller();
  c.handle(async () => null);
  await c.loadSettings();
  assert.equal(c.get('settingsStatus').dataset.state, 'error');
  assert.match(c.get('settingsStatus').textContent, /Reload/);
  assert.equal(c.get('settingsReload').disabled, false);
  assert.equal(c.get('settingsGrid').attributes['aria-busy'], 'false');
  c.handle(null);
  await c.loadSettings();
  assert.equal(c.get('settingsStatus').dataset.state, 'ready');
  assert.match(c.markup, /<label[^>]+for="setting-log_level"/);
  assert.equal(c.get('setting-log_level').attributes['aria-describedby'], 'setting-description-log_level setting-status-log_level');
  assert.equal(c.get('setting-save-log_level').disabled, true);
});

test('reloads retain drafts, edits made during the request, filter, and keyboard selection', async () => {
  const c = controller();
  await c.loadSettings();
  c.edit('log_level', 'debug');
  const input = c.get('setting-log_level');
  input.focus(); input.setSelectionRange(1, 3);
  c.get('settingsSearch').value = 'log'; c.filterSettings();
  const refresh = deferred();
  c.handle(url => url === '/api/settings' ? refresh.promise : Promise.resolve({ apiKey: false }));
  const first = c.loadSettings();
  const second = c.loadSettings();
  assert.equal(c.calls.filter(call => call.url === '/api/settings').length, 2);
  c.edit('sonarr_base_url', 'http://draft.invalid:8989');
  refresh.resolve(snapshot());
  await Promise.all([first, second]);
  assert.equal(c.get('setting-log_level').value, 'debug');
  assert.equal(c.get('setting-sonarr_base_url').value, 'http://draft.invalid:8989');
  assert.equal(c.document.activeElement.id, 'setting-log_level');
  assert.equal(c.document.activeElement.selectionStart, 1);
  assert.equal(c.document.activeElement.selectionEnd, 3);
  assert.equal(c.get('setting-item-sonarr_base_url').hidden, true);
  assert.match(c.get('settingsSummary').textContent, /2 unsaved changes/);
});

test('saving one field preserves other drafts made while pending and rejects repeated writes', async () => {
  const c = controller();
  await c.loadSettings();
  c.edit('log_level', 'debug');
  c.get('setting-save-log_level').focus();
  const write = deferred();
  c.handle((url, opts) => opts.method === 'PUT' ? write.promise : Promise.resolve(url === '/api/settings' ? c.data : { apiKey: false }));
  const pending = c.saveSetting('log_level');
  await c.saveSetting('log_level');
  assert.equal(c.writes().length, 1);
  assert.equal(c.get('setting-log_level').disabled, true);
  assert.equal(c.get('setting-save-log_level').disabled, true);
  c.edit('sonarr_base_url', 'http://draft.invalid:8989');
  c.data.fields.log_level.current = 'debug'; c.data.fields.log_level.overridden = true;
  write.resolve({ key: 'log_level' }); await pending;
  assert.equal(c.get('setting-sonarr_base_url').value, 'http://draft.invalid:8989');
  assert.equal(c.get('setting-log_level').value, 'debug');
  assert.equal(c.get('setting-save-log_level').disabled, true);
  assert.equal(c.get('setting-log_level').disabled, false);
  assert.match(c.get('setting-status-log_level').textContent, /Saved/);
  assert.equal(c.document.activeElement.id, 'setting-log_level');
});

test('failed secret saves retain the draft without rendering or echoing its value', async () => {
  const c = controller();
  await c.loadSettings();
  c.edit('tmdb_api_key', 'synthetic-replacement');
  c.handle(async () => null);
  await c.saveSetting('tmdb_api_key');
  assert.equal(c.get('setting-tmdb_api_key').value, 'synthetic-replacement');
  assert.equal(c.get('setting-save-tmdb_api_key').disabled, false);
  assert.equal(c.get('setting-status-tmdb_api_key').dataset.state, 'error');
  assert.doesNotMatch(c.get('setting-status-tmdb_api_key').textContent, /synthetic-replacement/);
  assert.doesNotMatch(c.markup, /synthetic-replacement/);
  assert.doesNotMatch(JSON.stringify(c.toasts), /synthetic-replacement/);
});

test('accepted secret saves clear immediately even when the follow-up read fails', async () => {
  const c = controller();
  await c.loadSettings();
  c.edit('tmdb_api_key', 'synthetic-replacement');
  c.edit('log_level', 'debug');
  const refresh = deferred();
  const refreshStarted = deferred();
  c.handle((url, opts) => {
    if (opts.method === 'PUT') return Promise.resolve({ key: 'tmdb_api_key' });
    if (url === '/api/settings') { refreshStarted.resolve(); return refresh.promise; }
    return Promise.resolve({ apiKey: false });
  });
  const pending = c.saveSetting('tmdb_api_key');
  await refreshStarted.promise;
  assert.equal(c.get('setting-tmdb_api_key').value, '');
  assert.equal(c.get('setting-log_level').value, 'debug');
  assert.doesNotMatch(c.markup, /synthetic-replacement/);
  refresh.resolve(null); await pending;
  assert.equal(c.get('settingsStatus').dataset.state, 'stale');
  assert.equal(c.get('setting-tmdb_api_key').value, '');
  assert.equal(c.get('setting-log_level').value, 'debug');
});

test('reset requires confirmation, can be cancelled, and preserves unrelated drafts', async () => {
  const c = controller();
  await c.loadSettings();
  c.edit('log_level', 'debug');
  c.edit('sonarr_base_url', 'http://draft.invalid:8989');
  await c.resetSetting('sonarr_base_url');
  assert.equal(c.writes().length, 0);
  assert.equal(c.get('setting-reset-sonarr_base_url').textContent, 'Confirm reset');
  assert.equal(c.get('setting-cancel-sonarr_base_url').hidden, false);
  c.cancelSettingReset('sonarr_base_url');
  assert.equal(c.get('setting-cancel-sonarr_base_url').hidden, true);
  assert.equal(c.document.activeElement.id, 'setting-reset-sonarr_base_url');
  await c.resetSetting('sonarr_base_url');
  await c.resetSetting('sonarr_base_url');
  assert.equal(c.writes().length, 1);
  assert.equal(c.writes()[0].opts.method, 'DELETE');
  assert.equal(c.get('setting-sonarr_base_url').value, '');
  assert.equal(c.get('setting-log_level').value, 'debug');
  assert.equal(c.get('setting-reset-sonarr_base_url'), undefined);
});

test('editing a reset confirmation cancels it, and a failed reset retains its draft', async () => {
  const c = controller();
  await c.loadSettings();
  await c.resetSetting('sonarr_base_url');
  c.edit('sonarr_base_url', 'http://draft.invalid:8989');
  await c.resetSetting('sonarr_base_url');
  assert.equal(c.writes().length, 0);
  const write = deferred();
  c.handle(() => write.promise);
  const pending = c.resetSetting('sonarr_base_url');
  await c.resetSetting('sonarr_base_url');
  assert.equal(c.writes().length, 1);
  write.resolve(null); await pending;
  assert.equal(c.get('setting-sonarr_base_url').value, 'http://draft.invalid:8989');
  assert.equal(c.get('setting-status-sonarr_base_url').dataset.state, 'error');
  assert.equal(c.get('setting-reset-sonarr_base_url').textContent, 'Reset override');
});

test('malformed snapshots leave existing edits intact and explain that the view is stale', async () => {
  const c = controller();
  await c.loadSettings();
  c.edit('log_level', 'debug');
  c.handle(async () => ({ fields: { log_level: null } }));
  await c.loadSettings();
  assert.equal(c.get('setting-log_level').value, 'debug');
  assert.equal(c.get('settingsStatus').dataset.state, 'stale');
  assert.equal(c.get('setting-save-log_level').disabled, false);
});

test('search describes empty matches without deleting hidden drafts', async () => {
  const c = controller();
  await c.loadSettings();
  c.edit('tmdb_api_key', 'synthetic-replacement');
  c.get('settingsSearch').value = 'no matching setting'; c.filterSettings();
  assert.equal(c.get('settingsEmpty').hidden, false);
  assert.match(c.get('settingsSummary').textContent, /0 of 3 settings · 1 unsaved change/);
  c.get('settingsSearch').value = 'poster'; c.filterSettings();
  assert.equal(c.get('settingsEmpty').hidden, true);
  assert.equal(c.get('setting-item-tmdb_api_key').hidden, false);
  assert.equal(c.get('setting-tmdb_api_key').value, 'synthetic-replacement');
});

test('configuration reload reads only its own source', async () => {
  const c = controller();
  await c.loadSettings();
  assert.deepEqual(c.calls.map(call => call.url), ['/api/settings']);
});
